### ISSUE TITLE
Building `baloo-test-chaos` error

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#1]
I was trying to build the chaos example and have incurred the following error when building:

```
In file included from ../../os/net/mac/gmw/gmw.h:62:0,
                 from ../../os/net/mac/gmw/gmw-noise-detect.c:55:
../../os/net/mac/gmw/gmw-types.h:67:17: error: 'TOGMW_CONF_MAX_SLOTS' undeclared here (not in a function)
../../Makefile.include:316: recipe for target 'obj_sky/gmw-noise-detect.o' failed
make: *** [obj_sky/gmw-noise-detect.o] Error 1
```
It seems like `TOGMW_CONF_MAX_SLOTS` is never defined in the codebase itself (except in the `gmw-types.h`). I.e.:

```
#define GMW_SCHED_SECTION_HEADER_LEN    (8)
typedef struct __attribute__((packed)) gmw_schedule {
  uint32_t time;                  /* multiple of GMW_CONF_PERIOD_TIME_BASE */
  uint16_t period;                /* multiple of GMW_CONF_PERIOD_TIME_BASE */
  uint16_t n_slots;
  uint16_t slot[TOGMW_CONF_MAX_SLOTS];
} gmw_schedule_t;
```

I was wondering how the value ends up being used (i.e. what you would reckon to be sensible values) and if I can safely define it at a `project-conf.h` level.

Again thanks for the great work on Baloo!

--------------
EDIT:

Could it perhaps be a typo?
All gwm macros seem to be prefixed as `GMW-*` and editing as follows seems to work:

```
#define GMW_SCHED_SECTION_HEADER_LEN    (8)
typedef struct __attribute__((packed)) gmw_schedule {
  uint32_t time;                  /* multiple of GMW_CONF_PERIOD_TIME_BASE */
  uint16_t period;                /* multiple of GMW_CONF_PERIOD_TIME_BASE */
  uint16_t n_slots;
  uint16_t slot[GMW_CONF_MAX_SLOTS];
} gmw_schedule_t;
```

**Comment by romain-jacob** [comment]
It is indeed a typo. Sorry about that. The correct macro name is GMW_CONF_MAX_SLOTS.

**Comment by romain-jacob** [comment]
I have pushed the fixed on the master branch.
