### ISSUE TITLE
Control packet Wiki - GMW_CONTROL_CLEAR

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#10]
I believe there is a typo in the [Control packet Wiki](https://github.com/ETHZ-TEC/Baloo/wiki/Baloo-control-packet#slot-array) for `GMW_CONTROL_CLEAR` instructions.

Clear flags are defined as `CLR` (instead of `CLEAR`) in the codebase:

```
os/net/mac/gmw/gmw-control.h:76:#define GMW_CONTROL_CLR_CONFIG(c)  ((c)->schedule.n_slots &= \
```

**Comment by romain-jacob** [comment]
Thanks, corrected.
