### ISSUE TITLE
Configurable pre_post_proc

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#11]
Currently the `pre_post_proc` struct gets configured on `gmw_start` and is constant throughout the whole protocol execution.

This means that at the end of each Baloo round we are forced to poll to execute the `post_process_current_round` and the `post_process_current_round` should they be defined.

```
    /* poll the post process */
    if(pre_post_proc.post_process_current_round) {
      process_poll(pre_post_proc.post_process_current_round);
    }

    /* wake-up earlier to execute the pre-process (if one is defined) */
    pre_process_offset = (!pre_post_proc.pre_process_next_round) ? 0 :
                         GMW_MS_TO_TICKS(GMW_CONF_T_PREPROCESS);
```

I was wondering if an extension to this is either planned by you guys, or a modification by PR is welcome.

The idea would be to either
1. Add a configurable flag section to the `struct gmw_pre_post_processes` which can allow to toggle the pre and post polls on or off.
2. Allow full configuration of the `struct gmw_pre_post_processes`, exposing methods to change its contents after the initial `gmw_start` call. This would allow to set the `post_process_current_round` field to `NULL` temporarily should be wish to not preempt.

Is it reasonable? The idea that certain protocols might wish to have back-to-back floods without being forced to preempt the app process before they are finished.

**Comment by romain-jacob** [comment]
> Allow full configuration of the struct gmw_pre_post_processes, exposing methods to change its contents after the initial gmw_start call. This would allow to set the post_process_current_round field to NULL temporarily should be wish to not preempt.

This is already implemented. It can be controlled via the [on_round_finished() callback](https://github.com/ETHZ-TEC/Baloo/wiki/Baloo-callbacks#4-the-on_round_finished-callback).
