### ISSUE TITLE
Multi-hop chaos

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#13]
I was playing a bit with Chaos and I have a number of questions. Everything was built on top of `baloo-chaos-test` running on 6 nodes on Flocklab.

`~`
1. How many chaos slots are executed in one Baloo/GMW slot.

As far as I understand for every slot the GMW determines if the current node is an initiator or a receiver, and based on that it will either execute `GMW_SEND_PACKET()` or `GMW_RCV_PACKET()`.

Going deeper into `GMW_SEND_PACKET()`, it is mainly made up of `GMW_START_PRIM(...)`, `GMW_WAIT_UNTIL(...)` and `GMW_STOP_PRIM()`.

When using the chaos primitive, `GMW_START_PRIM(...)` is assigned to `chaos_start(...)` and `GMW_STOP_PRIM()` is assigned to `chaos_stop()`.

From my understanding of chaos, it normally would autonomously terminate once all of the `CHAOS_FLAGS` are set. But by scheduling just one slot using GMW, isn't the protocol forced to terminate after just one flood? (So `chaos_stop()` is called independently on wether the node has received flags from all other nodes?).

Also is it safe to assume that the current setup only executes one chaos slot on the network?

`~`
2. Are flags carried over between slots?

As far as I currently understand chaos flags are not carried over between rounds, though my question is if I were to set `schedule.n_slots` to `2` or even `5`, would flags be carried over between these consecutive chaos slots? I currently suspect that flags are reset after each invocation of `chaos_start()` and subsequent `chaos_end()`.

`~`
3. Access to `CHAOS_FLAGS_FIELD`.
Is there currently an elegant way to access the `CHAOS_FLAGS_FIELD` from the `packet` field after a chaos slot has completed?

`~`
4. Multi-hop chaos.
When running the chaos example over a multi-hop network I seem to get the value of the initiator/host node being flooded to every node. Whereas every source node is only ever able to get their payload to their one-hop-neighbours.
Am I testing incorrectly?

`~`
5. Chaos and control packet.
I was just wondering how the presence of the control packet is handled with Chaos. I believe the packet reaches all the nodes in the network synchronizing them and determining the beginning of the Chaos protocol. Though what would be the recommended way to keep Chaos "going"?
I was mainly thinking of:
A) Scheduling "enough" `schedule.n_slots` to allow the protocol to finish. If these are not enough a new control packet in the next round (back-to-back) is sent out with more slots.
B) Using the `GMW_EVT_REPEAT_SLOT` feature to keep re-broadcasting until when all nodes are finished. As is mentioned in the wiki, though, there is no guarantee nodes will finish and they might miss subsequent control packets from the host should they overrun the `schedule.period`, overall desynchronizing.

**Comment by romain-jacob** [comment]
> 1. How many chaos slots are executed in one Baloo/GMW slot.

Baloo executes a complete "Chaos round" in a single slot. Indeed, Chaos terminates autonomously once all the flags have been set. What Baloo does is that it forces Chaos to terminate at the end of the slot (in case Chaos is not finished yet).

> 2. Are flags carried over between slots?

No.

> 3. Access to CHAOS_FLAGS_FIELD.

I don't think so. My first idea to do this would be to add a get_chaos_flag() function to `chaos.c` 

> 4. Multi-hop chaos.

Chaos is a bit tricky to configure; I managed to run it as expected on multi-hop setting, so I would assume there is something wrong in your code, but hard to say what.

> 5. Chaos and control packet

Again, the "whole" chaos round is executed in one single Baloo slot. Your task as a designer is to make that slot big enough such that the Chaos round has enough time to complete -- which is typically hard to predict, given the nature of Chaos.   
So the procedure would be: set outrageously long slot time (e.g. 1s), run Chaos on your network, see how long it actually takes and adjust the slot time length.

**Comment by swarth100** [comment]
> Again, the "whole" chaos round is executed in one single Baloo slot. Your task as a designer is to make that slot big enough such that the Chaos round has enough time to complete -- which is typically hard to predict, given the nature of Chaos.

Thank you so much for the thorough reply!

So yes a full Chaos round should be scheduled for execution within one Baloo slot (providing a big enough slot time).

I will try and give a go playing with the Chaos flags.
As you mention I will to try and expose the flags setters and getters, so that when `chaos_start` is called I can change the implementation of `chaos_set_flags()` to actually receive a set the initial flags to a predefined value.

This would potentially allow to schedule slots where only a sub-set of all the nodes are requested to communicate/aggregate their values.

Just a final question:
It is mentioned that "the control packet is always sent using Glossy", is it therefore impacted by `GMW_CONF_MAX_HOPS`?

Or simply, when using Baloo+Chaos, should I set a correct value to `GMW_CONF_MAX_HOPS` so that the Glossy-flooded Control packet reaches all of the nodes? (Even though Chaos itself does not make any use of `GMW_CONF_MAX_HOPS`?)

**Comment by romain-jacob** [comment]
`GMW_CONF_MAX_HOPS` is only a helper macro used in the estimation of the completion time of some primitives (atm, only Glossy).

There is no way of knowing a priori what the maximal hop count is. What one can do however is, estimate the required slot length of a Glossy flood for a given `GMW_CONF_MAX_HOPS`.
