### ISSUE TITLE
Impact of GMW_EVT_SKIP_SLOT on multi-hop networks

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#14]
I've been trying the `GMW_EVT_SKIP_SLOT` feature to decrease node power usage.

I've been experimentally seeing that `GMW_EVT_SKIP_SLOT` seems to prevent packet relaying across multi hop networks.

```
H<--------------------->S1<--------------------->S2

schedule.n_slots = 2
schedule.slots[0] = S1
schedule.slots[1] = S2
```

If on the second slot source node `S1` returns the pre-slot callback with `GMW_EVT_SKIP_SLOT` then `S2`'s packet will never be relayed to host node `H`.

This would seem like expected behaviour if you shut off the radio, though I was wondering if my testing is incorrect and this should not be the case.

**Comment by romain-jacob** [comment]
If I understand you correctly, yes, this is the expected behavior: if S1 skip the slot, its radio stays off. If S2 needs S1 to reach the host, then S2 will be unreachable.
