### ISSUE TITLE
Problems when using `GMW_PRIM_GLOSSY`

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#17]
I've been trying setting the `primitive` field of the control section of the control packet to `GMW_PRIM_GLOSSY` and it currently does not compile, I've tried the following fixes with no luck:

In `arch/platform/sky/gmw-conf-sky.h:112`:

FROM:
```
  #define GMW_PRIM_DEFAULT           GMW_PRIM_GLOSSY     /* default Glossy */
  #define GMW_PRIM_GLOSSY            0
  #define GMW_PRIM_CHAOS             1
```

TO:
```
  #define GMW_PRIM_GLOSSY            0
  #define GMW_PRIM_DEFAULT           GMW_PRIM_GLOSSY     /* default Glossy */
  #define GMW_PRIM_CHAOS             1
```

And In `arch/platform/dpp-cc430/gmw-conf-dpp-cc430.h:111`:

FROM:
```
  #define GMW_PRIM_DEFAULT           0     /* default Glossy */
  #define GMW_PRIM_CHAOS             1
```

TO:
```
  #define GMW_PRIM_GLOSSY            0
  #define GMW_PRIM_DEFAULT           GMW_PRIM_GLOSSY     /* default Glossy */
  #define GMW_PRIM_CHAOS             1
```

From what I see wherever `GMW_PRIM_CHAOS` is defined also is `GMW_PRIM_GLOSSY`, yet I cannot seem to quite get `GMW_PRIM_GLOSSY` to work, I was just looking for a more user readable approach than `config->primitive = 0;`

**Comment by romain-jacob** [comment]
As of now, the `GMW_PRIM_GLOSSY` macro is defined only when the [multi-mode feature](https://github.com/ETHZ-TEC/Baloo/wiki/feat-switching-primitives) is defined. If the feature is configured correctly (see wiki page), using `GMW_PRIM_GLOSSY` compiles fine (tried on the sky mote only). 

Having said that, it would indeed make sense to have `GMW_PRIM_GLOSSY` being always defined. I will correct that for the next release. Thanks :-)
