### ISSUE TITLE
SUSPENDED -> BOOTSTRAP Delay

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#18]
Hi @romain-jacob 

I was running some tests the other day and occasionally a node would miss the Control packet and get the following behaviour:

![image](https://imgur.com/C5ETp3k.png)

Node 8 misses the control packet, sleeps for the old round time (2s), wakes up again, and finally keeps the radio always on waiting for a new control packet.

The `src_on_bootstrap_timeout` function for node 8:

```
static uint32_t
src_on_bootstrap_timeout(void)
{
  leds_off(LEDS_GREEN);
  leds_on(LEDS_RED);
  return 0;
}
```

What I was expecting was the node to instantly keep the radio always on in case a control packet is missed.

From inspecting the `gmw.c` source I think what is happening is:

1) Missed Contorl slot
1) Calling `impl_sync_state = gmw_impl->on_control_slot_post(&control, sync_event, pkt_event);` with `sync_event=GMW_EVT_CONTROL_MISSED` which has ID 1
1) The `on_control_slot_post` returns `GMW_DEFAULT` meaning that `sync_state` gets assigned to `GMW_SUSPENDED`.
1) And then `process_poll` gets called, and I suspect that this is using the old, previous, `round` time, rather than the new value which has been set by the `on_slot_timeout` callback.
1) At the next iteration the state changes to `GMW_BOOTSTRAP` and thus the node instantly wakes up again to listen

So I was wondering if:
1) There is some extra configuration I should do to allow `on_bootstrap_timeout` to instantly set the new round time
1) If it is best to modify the `on_control_post` callback to return `GMW_BOOTSTRAP` rather than `GMW_DEFAULT` when `sync_event` is `GMW_EVT_CONTROL_MISSED`
1) Or if I'm completely missing the point :p

**Comment by romain-jacob** [comment]
The intent of the `on_bootstrap_timeout` callback is to put the node to sleep between bootstrapping attempts. So, this cb is only called when a node is already in BOOTSTRAPPING state. If that is the case, there is nothing you can do to "set" the round period (I am not too sure what you have in mind with 1.)

As for 2., you can definitely modify the return value of `on_control_post` to whatever you like. If you want to go to bootstrap directly whenever you miss a control packet, you can do so; just return `GMW_BOOTSTRAP`.

Hope that helps

**Comment by swarth100** [comment]
Thank you for your prompt reply!

I wad just wondering what you would think is the best strategy to use to ensure that a node instantly turns the radio back on after it detects the control packet is either missed or corrupted

I believe with my above configuration I am actually skipping the next round before listening again, and I’m currently having trouble as I change the round lengths during back-to-back floods

**Comment by romain-jacob** [comment]
If that's your wish, then option 2. is what you want.

**Comment by swarth100** [comment]
Thank you!!
