### ISSUE TITLE
Minimal Baloo Test

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#6]
I was testing a minimal Baloo configuration using 3 nodes.

```
ID  |  Type
----+-----
10  |  Host
 6  |  Src
 7  |  Src
```

I am working on top of the Baloo minimal example.

Out-of-the-box the nodes did not seem to be communicating as expected. Two nodes are only ever receiving 1 packet of information per schedule, when expecting 2. By doing some debugging, I saw that when running the scheduling would behave as follows:

```
SCHEDULE

Time Slot  | Node ID
-----------+--------
    00     |    10
    01     |    07
    02     |    06
```

Though when executing, I get the following logs:

```
Node 10 (Host)
[INFO:     0] PRE  [Time Slot: 0][Node ID: 10] [INITIATOR] Prepared Payload 10 19
[INFO:     0] POST [Time Slot: 0][Node ID: 10] [NOT INITIATOR]  Skip
[INFO:     0] PRE  [Time Slot: 1][Node ID: 10] [NOT INITIATOR]  Skip
[INFO:     0] POST [Time Slot: 1][Node ID: 10] [INITIATOR] INVALID LEN PACKET. Len: 0
[INFO:     0] PRE  [Time Slot: 2][Node ID: 10] [NOT INITIATOR]  Skip
[INFO:     0] POST [Time Slot: 2][Node ID: 10] [INITIATOR] received 7 19
[INFO:     0] time: 552, period: 2
[INFO:     0] [Node ID: 10] HOST received 1 of 3 packets
[WARN:     0] Missed 1 slots! 

Node 7 (Src)
[INFO:     0] PRE  [Time Slot: 0][Node ID: 7] [NOT INITIATOR] Skip
[INFO:     0] POST [Time Slot: 0][Node ID: 7] [INITIATOR] received 10 128
[INFO:     0] PRE  [Time Slot: 1][Node ID: 7] [NOT INITIATOR] Skip
[INFO:     0] POST [Time Slot: 1][Node ID: 7] [INITIATOR] HOST INVALID LEN PACKET. Len: 0
[INFO:     0] PRE  [Time Slot: 2][Node ID: 7] [INITIATOR] Prepared Payload 7 128
[INFO:     0] POST [Time Slot: 2][Node ID: 7] [NOT INITIATOR] Skip
[INFO:     0] [Node ID: 7] SRC received 1 of 3 packets
[WARN:     0] Missed 1 slots! Binary: 2


Node 6 (Src)
[INFO:     0] PRE  [Time Slot: 0][Node ID: 6] [NOT INITIATOR] Skip
[INFO:     0] POST [Time Slot: 0][Node ID: 6] [INITIATOR] received 10 105
[INFO:     0] PRE  [Time Slot: 1][Node ID: 6] [INITIATOR] Prepared Payload 6 105
[INFO:     0] POST [Time Slot: 1][Node ID: 6] [NOT INITIATOR] Skip
[INFO:     0] PRE  [Time Slot: 2][Node ID: 6] [NOT INITIATOR] Skip
[INFO:     0] POST [Time Slot: 2][Node ID: 66] [INITIATOR] received 7 105
[INFO:     0] [Node ID: 6] SRC received 2 of 3 packets
[WARN:     0] Missed 1 slots! Binary: 2

```

Which makes me think the dynamics are as follows:

TIME 0) Host Node 10 prepares packet, sends it and both source nodes receive it.
TIME 1)  Src node 6 prepares a packet, sends it and nobody receives it. Nodes 10 and 7 instead receive a packet of null length. By inspecting the data we read stale  memory, as the contents of the buffer were never overwritten.
TIME 2) Src node 7 prepares a packet, sends it, and all nodes receive it.

Also both Host and Source have the same callbacks registered:

```
gmw_init(...)
{
  /* load the host node implementation */
  host_impl->on_control_slot_post   = &host_on_control_slot_post_callback;
  host_impl->on_slot_pre            = &host_on_slot_pre_callback;
  host_impl->on_slot_post           = &host_on_slot_post_callback;
  host_impl->on_round_finished      = &host_on_round_finished;

  /* load the source node implementation */
  src_impl->on_control_slot_post    = &src_on_control_slot_post_callback;
  src_impl->on_slot_pre             = &host_on_slot_pre_callback;
  src_impl->on_slot_post            = &host_on_slot_post_callback;
  src_impl->on_round_finished       = &src_on_round_finished;
  src_impl->on_bootstrap_timeout    = &src_on_bootstrap_timeout;

  ...
}
```

So my question is, have I configured something completely wrong? The behaviour of the nodes does not seem to be impacted by topology (for as much as I can test). Or is this expected behaviour?

Swapping out Node 6 with another TelosB shows the same exact behaviour. If Node 7 is ordered second in the schedule (instead of third), its messages will not be reaching the other two nodes.

**Comment by romain-jacob** [comment]
Hi @swarth100 ,

It is a bit hard to say a priori, it seems you added/changed quite a few things from the baloo-minimal example, so hard to be sure.

One thing to look at: all your nodes seem to miss one slot (slot number 1). Likely, this is due to your pre-/post-slot callbacks overrunning. I am not sure what you are doing in these callbacks at the moment, but if you do eg a lot of prints, that may be the reason why things are taking too long...

I would try either to reduce the callback complexity, or increase the gap time (see https://github.com/ETHZ-TEC/Baloo/wiki/Baloo-Managing-time for details).

**Comment by swarth100** [comment]
Thank you so much for your prompt reply @romain-jacob !

It was indeed print statements that were messing up with the overall timing!
Removing all prints has all nodes receive messages on all slots

Out of interest, are all `DEBUG_PRINT_*` blocking in Contiki-NG? 
So should I try and aggregate results and possibly print them out on the `on_round_finished` callbacks?

Also I think I missed in the past the high levels of configurability of timings for slots and rounds, reading into it!

And overall, thank you all for this amazing library + middleware. Documentation is top-notch, and the codebase is incredibly easy to follow and use!

**Comment by romain-jacob** [comment]
Thanks @swarth100 , we did our best :-) The Wiki documentation is still a WiP, please let us know if you find some things unclear.

> Out of interest, are all DEBUG_PRINT_* blocking in Contiki-NG?
So should I try and aggregate results and possibly print them out on the on_round_finished callbacks?

I am not sure what you mean by "blocking". In short, the `DEBUG_PRINT_` macros are formatting debug messages, and store them into a buffer, that can be flushed over serial at a later point in time. This helps having a more predictable timing in time sensitive part of the code (e.g., the callbacks) by postponing the writing over serial. But putting the debug message together still take quite some time! If the prints are needed, you must make sure the gap time is large enough.

The `debug_print.h` utility is not part of Contiki at the moment. But we will eventually add it if/when Baloo is merged with the official Contiki-NG repository.
