### ISSUE TITLE
Location of new protocols

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#9]
I was wondering where to locate within the directory structure new protocols built on top of Baloo.

Looking at the existing implementations I mainly see two types of approach:
1. Modular such as `lwb`. All files live within `net/mac/gmw/lwb` and an API is exposed to the user. All Baloo callbacks are encapsulated within the `gmw-lwb` files.
2. A more experimental approach such as `sleeping-beauty` or `crystal`. All source for the algorithms lives within their example directory. All code is available to the user as the protocol is implemented directly within the user's code within the Baloo callbacks.

I completely understand how all protocols will start from approach (2), but I think off-the-shelf functionality can only be achieved with (1)-like implementations (i.e. a simple API that all can use).

Due to this I was wondering where consensus protocols (such as 2PC and 3PC) should be located. I don't think they would strictly belong within the `gmw` sections, or is it simply that all baloo-based implementations should currently be located there?

**Comment by romain-jacob** [comment]
This question concerns the Contiki-NG maintainers more than us I would say. Here is what I would propose:
- Generic MAC layers/tools could be in `os/net/mac`. In there, everything based on Baloo should be in the `gmw` directory imo.
- All the rest (everything non general/reusable) should remain in examples.

Now, if you implement 2PC and 3PC, and you want to make them available as a service, I am not sure how this can be integrated atm. I think if we follow the Baloo mindset, these should be implemented as "primitives" (rather complex one, but still). Then in your Baloo application, you would schedule one slot in a round to be a "2PC-slot"... That would be my first idea.

**Comment by swarth100** [comment]
Perfect perfect!

I will refactor everything in the `gmw` directory to allow for extensibility (as effectively 3PC builds on top of 2PC).

> Now, if you implement 2PC and 3PC, and you want to make them available as a service, I am not sure how this can be integrated atm. I think if we follow the Baloo mindset, these should be implemented as "primitives" (rather complex one, but still)

Ah, so my current approach was to implement 2PC as a protocol sitting on top of Glossy. Once results are measured on Flocklab I wanted to port it to Chaos in order to obtain results which can be directly compared to the 2PC implementation proposed by the "A2: Synchotron" paper (and thus have a direct algorithmic comparison for Baloo VS Synchotron.

I think I am close to pushing 2PC upstream in the next few days (implemented currently as a protocol sitting on top of gmw), and potentially we could then discuss drawbacks of the implementation within the PR, as it is always easier to talk with actual code at hand.

I was talking to Michael Breza the other day and we were thinking one of the challenges of consensus protocols is the idea that it really is a multiple-initiator problem. Any node should be able to initiate a consensus/agreement round when it needs to. This might slightly clash with Baloo's centralised design, though we were potentially thinking of introducing small 2PC extensions, such as an initial proposal round where a global time-slicing schedule is agreed upon (so any node can initiate a 2PC round only when it is scheduled as initiator). But that is really for the future.

Thanks once again for the prompt reply! WIll keep you updated

**Comment by romain-jacob** [comment]
I thought you might be going in that direction. One important note: Synchrotron and Baloo are similar in the concepts, but work on __different__ levels. Baloo is made to facilitate the design of network layers, Synchrotron is made to facilitate the design of primitives (anything Glossy-like, ie sequences of TX and/or RX and/or idle phases). Baloo is more similar to A2 than to Synchrotron.

The A2 paper did exactly what I was referring to: Use synchrotron to implement 2PC as a service to the application layer.

What would be really nice is to port Synchrotron into Baloo. Then, one could easily design a custom primitive (say 2PC), that can be used at the network layer protocol using Baloo...

**Comment by swarth100** [comment]
Okay, so I think I now understand and I do see the big picture. I think I do have an incorrect mental picture of Synchotron, where it is very similar to Baloo, as in it does everything Baloo does, but Baloo is more modular and much easier to use. I just wanted to elaborate a tiny bit on why I think 2PC is much more similar to LWB if compared to a dissemination primitive such as Glossy.

Uhmm.

And by rereading the paper, yes, it is stressed how "2PC" is a primitive built on top of Chaos. Though I feel like I don't personally see how 2PC could be a primitive itself. I really think primitives (as Baloo intends them) answer the question "what are the physics behind the packet transfer". And these are questions Glossy, Chaos, and newer alternatives such as "Mixer" address. It's really about the mechanics, the physics, the capture effect, the constructive interference. 

On top of these primitives come the protocols, which end up answering questions such as "what is the logic behind sending this packet?" or "what data should I be sending". And I think 2PC would belong to the latter, very similarly to LWB. The protocols need to be aware about the Baloo phases and about the lower-level details of how the chosen primitives work. Additionally the same protocol could be implemented using different primitives, as the protocol is primitive-independent (even though certain primitives facilitate certain protocols).

On top of the protocols comes the application (which A2 would call services). These are high-level functionalities that use the procotols to achieve something. The application is unaware of the primitives used, it just knows about the API of the protocol.

So I think I am really just looking at how the protocol code gets used:
- [2PC implemented within A2](https://github.com/iot-chalmers/a2-synchrotron/blob/1224860ff62db2e91af5ed0c6ab2da7ee66295d8/a2-synchrotron-contiki/apps/chaos/2pc/2pc-app.c)
- [LWB implemented within Baloo](https://github.com/ETHZ-TEC/Baloo/blob/master/examples/baloo-lwb/baloo-lwb-test.c)

Where the end product and abstraction is incredibly similar: an API is exposed and from a top application level said API can be used to achieve what the underlying protocol guarantees (Shared-bus-like data transfers in the case of LWB, and some basic agreement in the case of 2PC).

Am I incredibly incorrect to propose the following division?
```
Application      (A2 services, or high level applications)
-------------
Protocols        (LWB, 2PC, Paxos)
-------------
Primitives       (Chaos, Glossy, Mixer)
``

**Comment by romain-jacob** [comment]
I don't think there is a fundamental right or wrong in either way of doing the partitioning between "primitives" and "protocols". 

My vision of a "primitive" in the sense of Baloo is: "something that executes an atomic communication task" (i.e., without intervention of the NET layer). It does not really matter that the "communication task" is. Certain primitives are better suited for certain tasks:
One-to-many -> Use Glossy
Many-to-many -> Use Chaos/Mixer/else

2PC can be seen as a "communication task", where each node has a initial value to propose, and at the end should know about the final value. There is no need for the NET layer/application to intervene in the whole process. 
But you can also view 2PC as a "protocol" similar to LWB, where your return to the NET layer after each transmission/reception.

Fundamentally, both are fine. My intuition is that the first approach would be much more efficient, but maybe I am wrong.

**Comment by swarth100** [comment]
I think it is surely worth investigating :)

The A2 guys have solid results on their end, and I think with data at hand it might be easier to make deductions

> There is no need for the NET layer/application to intervene in the whole process.

Ah, so regarding this I think 2PC could expose application-defined callbacks for the voting stage. 
Within chaos aggregation is much "crude" in some way as all aggregation logic is predefined and the application is not aware (so yeah r/w buffers could be put in place, but the idea is for the net layer to handle all the logic, the application is never preempted). And in this case I completely agree. 2PC with chaos-like aggregators (i.e. max/min payload) used within the voting stage is, and should be considered as, a primitive.

The moment application input is requested it turns more into a protocol as after each round the app is required to potentially make a choice based on the payload disseminated by Glossy.

Thank you so much for clarifying this (and for your time)!
